# Generated by Django 5.2.8 on 2025-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="address",
            field=models.TextField(blank=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="settlement",
            name="map_script",
            field=models.TextField(
                blank=True,
                help_text="Вставьте скрипт карты сюда",
                verbose_name="Код карты (Яндекс/Google)",
            ),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="URL псевдоним"),
        ),
    ]
