# Generated by Django 5.2.8 on 2025-11-30 23:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_avatar_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.avatar_filename,
                verbose_name="Аватарка",
            ),
        ),
    ]
