# Generated by Django 5.2.8 on 2025-11-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер участка')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь (сотки)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (руб)')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('reserved', 'Забронирован'), ('sold', 'Продан')], default='free', max_length=20, verbose_name='Статус')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.settlement', verbose_name='Поселок')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
    ]
