# Generated by Django 5.2.8 on 2025-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="has_electricity",
            field=models.BooleanField(default=False, verbose_name="Электричество"),
        ),
        migrations.AddField(
            model_name="plot",
            name="has_gas",
            field=models.BooleanField(default=False, verbose_name="Газ"),
        ),
        migrations.AddField(
            model_name="plot",
            name="has_water",
            field=models.BooleanField(default=False, verbose_name="Водопровод"),
        ),
    ]
