# Generated by Django 5.2.8 on 2025-11-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staticpage",
            options={
                "verbose_name": "Статическая страница",
                "verbose_name_plural": "Статические страницы",
            },
        ),
        migrations.AddField(
            model_name="staticpage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pages/", verbose_name="Фото страницы"
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="slug",
            field=models.SlugField(
                help_text="about, infrastructure",
                verbose_name="URL страницы (about, infrastructure)",
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок страницы"),
        ),
        migrations.AlterUniqueTogether(
            name="staticpage",
            unique_together={("settlement", "slug")},
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название документа"),
                ),
                ("file", models.FileField(upload_to="docs/", verbose_name="Файл")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Если галочка не стоит, видят только авторизованные жители",
                        verbose_name="Виден всем?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.settlement",
                        verbose_name="Поселок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Фотография"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.settlement",
                        verbose_name="Поселок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото галереи",
                "verbose_name_plural": "Галерея",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Картинка новости",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "content",
                    models.TextField(verbose_name="Полный текст новости (HTML)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.settlement",
                        verbose_name="Поселок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-created_at"],
            },
        ),
    ]
